### ISSUE TITLE
How to download TYGEM/Tom game after 2017?

### ISSUE THREAD

**Issue by pangafu** [yenw/computer-go-dataset#1]
Does there a way to download TYGEM or Tom games after 2017

**Comment by yenw** [comment]
* Q1: Does there a way to download Tom games after 2017.
   * A1: The service of Tom has been closed.

* Q2: Does there a way to download TYGEM games after 2017.
  * Method1:
     * Step1: You can using an api to get the newest **3000** "9d vs 9d" game info.
     * Step2: Parser this info by [KifuInfoParser](https://github.com/yenw/computer-go-dataset/blob/master/TYGEM/KifuInfoParser.cpp)
     * Step3: Download the gib kifu by game_id.
     * Step4: Filter kifu by [GibParser#L112](https://github.com/yenw/computer-go-dataset/blob/master/TYGEM/GibParser.cpp#L112)
     * Step5: Convert gib to sgf by [GibParser](https://github.com/yenw/computer-go-dataset/blob/master/TYGEM/GibParser.cpp)
     * Step6: Do Step1-5 everyday !!! 
     * PS: I'm feeling too tired to do this. So I stop download it at 2017.01.01.
  * Method2:
     * Step1: Download all 900,000,000+ gib kifu at TYGEM.
     * Step2: Select all 9d vs 9d games.

**Comment by pangafu** [comment]
@yenw thanks a lot~
Where can I download gib kifu of TYGEM in Method2@TYGEM

**Comment by yenw** [comment]
@pangafu 
You need to analyse the TCP stream data by Wireshark when you download kifu at TYGEM.

By the way, may be you need a 4T hard disk to store all gib kifu.

**Comment by pangafu** [comment]
@yenw sound so complex...
