### ISSUE TITLE
convert TOM dataset and use it in java.

### ISSUE THREAD

**Issue by adiv1212** [yenw/computer-go-dataset#5]
Hello I'm using TensorFlow in java and I cant figure out how to use your TOM dataset for my linear regression module.
Which library would you recommend me to use in this case?
Thank you in advance.

**Comment by yenw** [comment]
You can use the [Converter_Tom.py](https://github.com/yenw/computer-go-dataset/blob/master/Tom/Converter_Tom.py) tool to convert it to SGF, and then use Java's SGF library to read these files.
